version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-API
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_TOKEN_LIMIT=20
      - USER_TOKENS=["userToken"]
      - ADMIN_TOKEN="adminToken"
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - RABBIT_URL=rabbit
    depends_on:
      - rabbit
  worker:
    build:
      context: .
      dockerfile: Dockerfile-Worker
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - RABBIT_URL=rabbit
    volumes:
      - engines:/app
    depends_on:
      - rabbit
      - engine_swipe
  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  engine_swipe:
    build:
      context: .
      dockerfile: Engines/SWIPE/Dockerfile
    volumes:
      - engines:/engines/swipe

volumes:
  engines:
