version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-API
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_TOKEN_LIMIT=5000
      - USER_TOKENS=["dev"]
      - ADMIN_TOKEN="adminToken"
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - RABBIT_URL=rabbit
    depends_on:
      - rabbit
  worker:
    build:
      context: .
      dockerfile: Dockerfile-Worker
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - RABBIT_URL=rabbit
    volumes:
      - swipe:/app/engines/swipe
      - diamond:/app/engines/diamond
      - databases:/app/databases
    depends_on:
      - rabbit
      - engine_swipe
      - engine_diamond
  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  engine_swipe:
    build:
      context: .
      dockerfile: Engines/SWIPE/Dockerfile
    volumes:
      - swipe:/app
  engine_diamond:
    build:
      context:  .
      dockerfile: Engines/DIAMOND/Dockerfile
    volumes:
      - diamond:/app

volumes:
  engines:
  swipe:
  diamond:
  databases:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/pauliusmilmantas/Desktop/Baigiamasis/Databases